import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import "../globals.css";
import { getMessages } from 'next-intl/server';
import { Alexandria } from 'next/font/google';
import Footer from '@/components/shared/footer';
import Navbar from '@/components/shared/navbar';

const alexandria = Alexandria({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-alexandria'
})



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params||"ar";
  const messages = await getMessages();
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body
        dir={locale === "ar" ? "rtl" : "ltr"}
        className={`${alexandria.className} antialiased text-main-navy`}
      >
        <NextIntlClientProvider messages={messages} locale={locale} >
          <Navbar/>
          {children}
          <Footer/>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
